cmake_minimum_required(VERSION 3.16)
project(rate_training_system LANGUAGES CXX)
set(CMAKE_CXX_STANDARD 17)
find_package(gz-sim8 REQUIRED)
find_package(gz-plugin2 REQUIRED COMPONENTS register)
add_library(rate_training_system SHARED RateTrainingSystem.cpp)
target_link_libraries(rate_training_system PRIVATE gz-sim8::gz-sim8 gz-plugin2::register)
add_library(imu_random_walk_system SHARED ImuRandomWalkSystem.cpp)
target_link_libraries(imu_random_walk_system PRIVATE gz-sim8::gz-sim8 gz-plugin2::register)
