from pathlib import Path
import json,hashlib,datetime,ast
V=Path('@DRL_ROOT_WINDOWS@/experiments/robustness_v1_20261002/v48_fixed_lr3e5');PRE=V/'memory_gate_revision2';R=V/'backtracking_revision3';T=R/'training';D=R/'development';X=R/'execution';P=Path('@DRL_ROOT_WINDOWS@/rl_rate_ctrl_refactor')
j=lambda p:json.loads(p.read_text());local=lambda p:Path(str(p).replace('/mnt/e/','E:/'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest();put=lambda p,v:p.write_text(json.dumps(v,indent=2));linux=lambda p:str(p).replace('E:/','/mnt/e/').replace('E:\\','/mnt/e/').replace('\\','/');win=lambda p:str(p).replace('/','\\')
a=j(R/'offline/admission.json');assert a['passed'] and a['formal_updates']==0 and a['disposable_optimizer_updates']==6 and a['step18_matches_diagnosis']
lf=V/'training/ledger.json';l=j(lf);assert l==j(R/'original_ledger_stopped.json') and l['stopped'] and l['charged_native']==608641 and l['formal_optimizer_updates']==17 and not l['reservations']
for path,h in j(PRE/'frozen_inputs.json').items():assert sha(local(path))==h
for path,h in j(T/'carried_inputs.json')['sha256'].items():assert sha(local(path))==h
p=j(T/'protocol.json');contract=dict(approved=True,version='backtracking_revision3',resume_global_update=17,batch_anchor_global_update=10,source_resume=j(T/'resume_step17.json'),effective_rules=j(T/'effective_rules.json'),strict_LR_single_variable=False,protocol_revisions=['smooth_start_revision1: adaptive smooth every update','memory_gate_revision2: historical memory quantiles diagnostic all batches','backtracking_revision3: fixed13 backtracking scales and strict float64 bias'],original_guards_unchanged=True,remaining_captures=14,total_captures=28,total_updates=40,final40_only_54_development=True,training_limit=2000000,development_limit=3000000,charge_preserved=608641,max_training_charge=1266641,no_automatic_retry=True)
put(R/'revision_contract.json',contract)
files=[T/'protocol.json',T/'effective_rules.json',T/'runtime_replacement.json',T/'carried_inputs.json',T/'resume_step17.json',T/'development_design.json',D/'protocol_frozen.json',D/'frozen_design.json',D/'amendment.json',R/'revision_contract.json',R/'offline/admission.json']+list(T.glob('runtime/*.py'))+list(D.glob('runtime/*.py'))+list(T.glob('templates/*.json'))+list(D.glob('templates/*.json'))+list((T/'training/batch_0').glob('*'))
files=[f for f in files if f.is_file()];put(R/'frozen_inputs.json',{linux(f):sha(f) for f in files});put(X/'windows_config.json',dict(owner_script=linux(T/'runtime/batch_driver.py'),linux_root=linux(T),observer_job='pending_gateway'))
ad=j(PRE/'execution/admission.json');ad.update(root=win(X),work_root=win(T),runtime=win(T/'runtime'),canonical_ledger=win(lf),sha256={win(f):sha(f) for f in files},offline_validation=win(R/'offline/admission.json'));put(X/'admission.json',ad)
note='\n\n2026-10-09 authorized V48 backtracking_revision3: fixed scales 2^-i for i=0..12 (minimum1/4096), all original guards retained; additional float64 batch/A bias <=1e-4-1e-10, nonzero actual parameter/action change required; every proposal recorded and only accepted nonzero steps counted. Exhaustion stops without retry. Resume exact17 actor/Adam/RNG/permutations/positions from protected pre18 checkpoint; retain original batch-start10 actor/optimizer/RNG and comparison anchor, never reset allowance at17. Existing1..17 and14captures copied/carried, not rerun;608641 charge retained. Integrated isolated18..20 plus exact replay passed (six disposable updates, zero native/formal); step18 matches diagnosis. Remaining14 captures and18..40, final40-only54 evaluation,2m/3m,holdouts unchanged. Rejection log now accurately says batch-start rollback, while latest accepted checkpoint remains separate. Three explicit revisions: smooth adaptation from1, memory diagnostic all batches, fixed extended backtracking; no strict LR-only causal attribution. Native binaries/physical acceptance unchanged. See backtracking_revision3/offline/admission.json and revision_contract.json.\n'
for f in [P/'TRAINING_PARAMETERS.md',P/'docs/TRAINING_STARTUP_RUNBOOK.md']:
 with f.open('a',encoding='utf-8') as stream:stream.write(note)
(P/'docs/V48_BACKTRACKING_REVISION3_20261009.md').write_text('# V48 backtracking_revision3\n'+note+'\nPublic entry: scripts/supervise_training.py --config '+win(X/'admission.json')+' start --run-root '+win(X)+'\n',encoding='utf-8')
l.setdefault('runtime_replacements',[]).append(dict(id=p['sync_runtime_id'],approved=True,historical_charge=608641,historical_optimizer_updates=17,historical_attempt_count=14,original_stop_reason=l.get('stop_reason'),reason='Fixed finite extended backtracking, exact17 resume with batch10 anchor',contract=linux(R/'revision_contract.json')));l['stopped']=False;l['stop_reason']='Explicit backtracking_revision3 continuation; old failures preserved';tmp=lf.with_suffix('.tmp');put(tmp,l);tmp.replace(lf)
put(V/'active_revision.json',dict(revision='backtracking_revision3',root=str(R),status=str(T/'status.json'),canonical_training_ledger=str(lf),canonical_development_ledger=str(V/'development/ledger.json'),launch_pending=True,utc=datetime.datetime.now(datetime.timezone.utc).isoformat()))
print(json.dumps(dict(ready=True,charge=608641,updates=17,files_frozen=len(files))))
