from pathlib import Path
import json,hashlib,datetime
V=Path('@DRL_ROOT_WINDOWS@/experiments/robustness_v1_20261002/v48_fixed_lr3e5');T=V/'training';D=T/'jobs/train_b0_p0/candidate/noise200_hover_hold/seed_480101'
j=lambda p:json.loads(p.read_text(encoding='utf-8'));sha=lambda p:hashlib.sha256(p.read_bytes()).hexdigest()
r=j(D/'result.json');a=j(D/'combined_audit.json');s=j(D/'sync_audit.json');ex=j(D/'export_status.json');l=j(T/'ledger.json')
assert r['steps']==2048 and r['survived_2048'] and r['physical_failure'] is None and a['passed'] and s['passed'] and ex['success']
assert l['attempts'][0]['status']=='audited' and l['attempts'][0]['charge']==43457
for p,h in j(V/'v47_ledgers_before.json').items():assert sha(Path(p.replace('/mnt/e/','E:/')))==h
q=dict(recorded_utc=datetime.datetime.now(datetime.timezone.utc).isoformat(),first_scheduled_capture_passed=True,qualification_extra_samples=0,job='train_b0_p0',case=r['case'],seed=r['seed'],model_id=r['nn_final_audit']['model_id'],steps=2048,native_NN=43457,native_PID=0,includes_warmup=True,original100Hz_RMSE_deg_s=r['axis_rmse'],native_consumed_RMSE_deg_s=a['native_RMSE'],native_reward_sum=a['native_reward_sum'],max_gap_us=a['native_max_gap_us'],history_error=a['history_reconstruction_error'],sync=s,export_success=True,owned_cleanup_completed_before_next_job=True,next_status=j(T/'status.json'),training_ledger_snapshot=dict(charged=l['charged_native'],reserved=l['reservations'],limit=l['native_limit'],formal_updates=l['formal_optimizer_updates']),development_ledger=j(V/'development/ledger.json'),v47_ledgers_unchanged=True,holder=j(V/'execution/holder_identity.json'),observed_running_PX4_pid=624159,observed_running_PX4_sha256='6bf92a950c87f04668e5d313100876a83be1b57236df2ee4c007f53313dd025e',evidence_sha256={str(p):sha(p) for p in [D/'result.json',D/'combined_audit.json',D/'sync_audit.json',D/'export_status.json']},overall_training_complete=False)
(V/'first_capture_verification.json').write_text(json.dumps(q,indent=2))
with Path('@DRL_ROOT_WINDOWS@/rl_rate_ctrl_refactor/docs/TRAINING_STARTUP_RUNBOOK.md').open('a',encoding='utf-8') as f:f.write('\n\n## 2026-10-09 V48 first scheduled capture passed\n\nIndependent holder2380 (outside observation Job), locked driver624109, first train_b0_p0/noise200_hover_hold/480101/A2428576135 completed2048; explicit export, full original audit, exact1ms synchronization and ownership cleanup passed. NN43457/PID0 including warmup settled to fresh training ledger; second scheduled train_b0_p1 automatically started with47000 reserved. Formal updates0, development0; this is collection-chain validation, not trained-policy acceptance. Original100Hz R/P/Y RMSE0.222708828/0.207432659/0.200250980 deg/s; native0.222720002/0.207432726/0.199611494. Maxgap1000us,history reconstruction error0. Running PX4 /proc/exe hash matched qualified sync2. V47 ledgers unchanged. Evidence: experiments/robustness_v1_20261002/v48_fixed_lr3e5/first_capture_verification.json. Frozen28/40/54 plan continues autonomously; any actual failure stops without retry. No model promoted or holdout accessed.\n')
print(json.dumps(dict(first_capture_passed=True,charged=l['charged_native'],status=q['next_status'],evidence=str(V/'first_capture_verification.json'))))
