from pathlib import Path
import json,hashlib
N=Path('@DRL_ROOT_WINDOWS@/experiments/robustness_v1_20261002/native_fresh_batch_rp_v47');O=N.parent/'v48_lr_offline_admission1';T=O/'prepared_training';P=Path('@DRL_ROOT_WINDOWS@/rl_rate_ctrl_refactor/docs')
j=lambda p:json.loads(p.read_text(encoding='utf-8'));a=j(O/'admission.json');ph=j(O/'phase_diagnostic.json');prep=j(O/'preparation.json');protocol=j(T/'protocol.json')
design=j(N/'development_recovery1/frozen_design.json');design.update(status='prepared_not_executed',jobs=[dict(index=k+1,case=case,seed=seed,label=label,profile='baseline' if label=='pid' else 'candidate') for k,(case,seed,label) in enumerate((c,s,l) for c in protocol['development']['cases'] for s in [480301,480302] for l in ['pid','A','candidate'])],native_limit=3000000,NN_per_episode=47000,PID_per_episode=56000,all54_before_decision=True,no_heldout=True,no_automatic_promotion=True,no_retry=True)
(T/'development_design.json').write_text(json.dumps(design,indent=2))
lines=[]
def add(v=''):lines.append(v)
def table(headers,rows):
 add('| '+' | '.join(headers)+' |');add('| '+' | '.join(['---']*len(headers))+' |')
 for row in rows:add('| '+' | '.join(map(str,row))+' |')
 add()
add('# V48 固定学习率离线准入与实施约束 — 2026-10-09\n')
add('结论：预定的第 20、30、40 步 3e-6 / 3e-5 离线对照全部通过原守卫和动作变化 ≥5× 准入。它只证明这三个历史局部状态上步长可以有效扩大，不证明从 A 重新训练 40 步一定成功，更不证明闭环 pitch 改善。已准备训练入口并完成 8 项测试，尚未启动 native。A 仍为当前模型，V47 final40 不晋级。\n')
add('## 严格配对与结果\n')
add('每对从同一个可信 pre_update_recovery.pt 恢复 actor、Adam moments/step、随机状态、采样排列/游标和 objective alpha；同一历史行为数据、相同 2000 条 minibatch 及权重（SHA256 匹配），唯一改变 optimizer LR。三个 1× 结果与原保存 actor 位级一致；未扫描其他学习率、未使用开发数据训练、未访问 holdout。历史数据只用于这 6 次一次性离线优化，不计为新在线采样，不写回正式 checkpoint。\n')
table(['步骤','1× 动作RP RMS','10× 动作RP RMS','倍数','10× 参数L2步长','10× KL','最小分层 ESS','回退比例'],[[c['step'],f"{c['pairs'][0]['guard_action_RP_rms']:.9g}",f"{c['pairs'][1]['guard_action_RP_rms']:.9g}",f"{c['action_rms_ratio']:.7f}",f"{c['pairs'][1]['step_parameter_L2']:.9g}",f"{c['pairs'][1]['result']['KL']:.9g}",f"{min(c['pairs'][1]['result']['stratum_ESS_fraction']):.9f}",c['pairs'][1]['result']['scale']] for c in a['comparisons']])
add('动作单位为归一化力矩，RMS 在同一固定 guard corpus 上对 roll/pitch 及样本取均方。三个 10× 对照的 yaw 动作差均为 0，冻结 buffers 全部相等，数值全部有限；投影范数保留比例约 0.998541、0.993380、0.999947。\n')
table(['步骤','10× likelihood ratio范围','最大cost_delta','最大逐步cost_delta','全局A权重变化','全局A bias变化','全局A动作最大变化'],[[c['step'],f"{c['pairs'][1]['result']['ratio_min']:.7f}–{c['pairs'][1]['result']['ratio_max']:.7f}",f"{max(c['pairs'][1]['result']['cost_delta']):.9g}",f"{max(c['pairs'][1]['result']['cost_delta_previous']):.9g}",f"{c['pairs'][1]['result']['global_A_weight_relative']:.9g}",f"{c['pairs'][1]['result']['global_A_bias_change']:.9g}",f"{c['pairs'][1]['result']['global_A_guard_action_change']:.9g}"] for c in a['comparisons']])
add('原守卫全部保留：总 KL≤0.002，RP 单轴 KL≤0.001，分层 KL≤0.004，整体/分层/组加权 ESS≥0.98，ratio∈[0.5,2]，九项 cost_delta 及相对前一步 cost_delta 各≤1e-6，输出头相对权重变化≤0.01、bias≤1e-4、动作最大变化≤0.002；批内参考及全局 A 两套检查均在。PPO clip±0.05、梯度 norm clip0.5、64 次投影和原四档回退保持。完整逐轴/逐层数组见 admission.json。\n')
add('## 首 3 秒权重诊断：不能直接宣布足够\n')
add('五个场景组各占 0.2，每组 first3/later 各占一半；每步 2000 条中共 1000 条来自首 3 秒，1000 条来自后 17.48 秒，因此首段每秒采样密度为后段的 5.8267 倍。quiet 组由 quiet/上移/下移三条均分，采用确定性 66/67 分配，组权重不因扩充增加。\n')
add('但 pitch 单位时间代价 first3=0.7·e²/(0.5²+e²)，later=0.5·e²/(0.2²+e²)，e 单位 deg/s。近零曲率之比仅 0.224；在 e=0.1 时导数分别 0.51775/1.6，而 e=0.5 时为 0.7/0.23781。首段较宽尺度对小误差更宽容，却对部分较大误差具有更高斜率，不能概括成首段统一偏轻。误差很大时两者都饱和。\n')
add('以下为原训练批次 1/2/3 的实际 pitch 代价积分；首段虽有较大 RMSE，其积分通常仅占全段约一成。采样等权不等于回报各相位等权：30 s 折扣的 reward-to-go 混合后续相位、轴和终端项，再经组间 baseline 与共同优势归一化；下表及解析导数不是策略梯度，不能据此证明权重足够或不足。此次保持全部权重和尺度不变。\n')
table(['原批次','工况','相位','pitch RMSE deg/s','pitch代价积分','|e|≥该相位尺度比例'],[[r['batch'],r['case'],r['phase'],f"{r['pitch_RMSE_deg_s']:.6f}",f"{r['pitch_cost_integral']:.6f}",f"{r['fraction_abs_error_above_scale']:.4f}"] for r in ph['rows'] if r['case'].startswith('low_')])
add('## 下一版完整关键约束（准备完成，未执行）\n')
add('1. **从 A 重新开始**，不是从 V47 final40 接着训。A 模型 ID 2428576135，binary SHA256 `0bdfed33c8a2ab7ae5901d522f8c493184924c633c25e4ad129d5da4f8c24f1e`；新 Adam 无历史 moments。仅 154 个 RP 输出头参数更新；主干/yaw/gate 冻结，独立网络不引入 PID 教师或位置/姿态真值。\n')
add('2. 学习率固定 **3e-5**，不扫描、不自适应。为保留 V47 的目标时序，更新 1–10 仍 alpha=1 且原平滑梯度≤10% 检查硬停；11 起应用原只降不升的全局平滑 alpha（目标 0.099、复测≤0.1，非有限硬停）；不是从 V47 末值 0.2820 开始。首次及第二批 memory/速度覆盖原硬门槛保留；21 起历史 memory 分位仅诊断，必须由本次 batch0 真实覆盖报告证明初始通过，不沿用旧通过标记。4000/s、其余奖励、首段权重和物理终止条件不变。\n')
add('3. **4 批×7 条新采集×10 次更新 = 28 条新采集、40 次更新**。每批仅使用本批当前行为 actor 采集的七条，继承新运行前一批的 Adam moments，不混入旧行为数据。每次 2000 条加权 minibatch，AR 探索 std0.001 和20 ms时常保持。入口校验新根目录、job、batch、seed、case、actor ID、已审计状态并拒绝旧/重复数据。\n')
add('4. 训练 native 硬上限 **2,000,000**，28 条各预留47,000合计 **1,316,000**；剩余预算不授权额外采集/探测/自动重试。进入/评分/失败均计费；未知失败按预留保守计费。任何物理、存活不足2048、同步>4ms、有限值、数据或优化守卫失败立即停止保留证据。沿用本地每条1800s超时触发停止；总耗时不能从离线单步推断。\n')
add('5. 候选预先固定为第 **40 次正式更新**，不据开发分数选择中间 checkpoint。每批 checkpoint 仅作审计/恢复证据。达到40后停止训练、冻结 actor/hash，再完整开发验收；不能仅因成功启动或存活而宣布完成。\n')
add('6. 验收 **九工况×新种子480301/480302×PID/A/final40 = 54 项**，独立硬预算 **3,000,000**，36 NN×47,000 +18 PID×56,000=**2,700,000**预留，无自动重试/额外筛选。完整矩阵前不决策，原逐轴RMSE/P99、电机、低速全段/巡航/覆盖、保护工况及重复范围规则不变；原100 Hz与实际消费参考native两种口径并列，首3秒不删。holdout12701/12702封存，上游PX4/PID、plant、传感器、控制分配及合格native二进制不变。\n')
add('7. 这是一版受限假设检验。离线通过不等于闭环通过；若学习量扩大仍未过全矩阵，保留 A，不放宽门槛，另立下一假说。新开发种子无法消除所有闭环初始状态差异，不能把与V47历史分数差简单归为LR的因果效应。\n')
add('## 入口与测试\n')
add('独立准备目录：`'+str(T)+'`。`protocol.json` 中 `authorized=false`；默认 entry 只作哈希、预算和准入检查，`--run` 在未获启动决定时会拒绝。准备过程修复了旧续训 updater 不支持 batch0 的初始化路径，加入新批次来源检查；未修改旧实验代码。native runner 的导出/崩溃诊断沿用已测试恢复版，训练账本上限仍为2m。\n')
add('已通过 8 项测试：合法新采集、拒绝历史数据、重复数据、错误 actor、错误 seed、新 Adam 状态为空、跨批 moments 保留且 LR 不回落、未授权 native 启动拒绝；入口预检和全部准备脚本语法检查通过。没有做真实新采集，因此整轮采集→优化→评估链尚未端到端验证。评估矩阵已冻结为 development_design.json，评估执行器需在冻结候选后按该矩阵绑定，不能复用旧种子硬编码。\n')
add('```powershell\n# 零 native 预检\nwsl.exe -d Ubuntu-22.04 -- @LINUX_HOME@/rl_rate/.venv/bin/python -B @DRL_ROOT_LINUX@/experiments/robustness_v1_20261002/v48_lr_offline_admission1/prepared_training/entry.py\n# 零 native 测试\nwsl.exe -d Ubuntu-22.04 -- @LINUX_HOME@/rl_rate/.venv/bin/python -B @DRL_ROOT_LINUX@/experiments/robustness_v1_20261002/v48_lr_offline_admission1/test_prepared.py\n```\n')
add('未来启动命令为同一 entry 加 `--run`，但本轮不设置授权、不执行该命令。当前没有新正式模型或训练日志；仅诊断和测试产物。\n')
for name in ['plan.json','admission.json','phase_diagnostic.json','preparation.json','test_prepared.log']:add('- `'+str(O/name)+'`')
dest=P/'V48_LR_OFFLINE_ADMISSION_20261009.md';assert not dest.exists();dest.write_text('\n'.join(lines),encoding='utf-8')
old=P/'V48_OFFLINE_DIAGNOSIS_AND_PROPOSAL_20261009.md'
with old.open('a',encoding='utf-8') as f:f.write('\n\n## 后续状态\n\n固定 20/30/40 步离线学习率对照现已完成并通过，入口已准备但尚未启动；最新证据、完整执行约束与首3秒权重分析见 [V48_LR_OFFLINE_ADMISSION_20261009.md](V48_LR_OFFLINE_ADMISSION_20261009.md)。原“尚未执行”段落保留为当时提案记录。\n')
print(json.dumps(dict(report=str(dest),offline_passed=a['passed'],unit_tests=prep['unit_tests'],native_calls=0,formal_updates=0)))
